services:
  - type: web
    name: client-website-backend
    env: node
    buildCommand: npm install && npm rebuild bcrypt
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000